spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root #???
    password: ai_gc_kid_666 #????
    url: jdbc:mysql://localhost:3306?characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8
server:
  servlet:
    context-path: /ai/kids
  port: 80
data:
  redis:
    host: localhost
    # Redis???????
    port: 6379
    lettuce:
      pool:
        #????????????????????
        max-active: 100
        # ???????????
        max-idle: 10
        # ???????????????????????
        max-wait: 100000
    # ??????????
    timeout: 5000
    #??????0????
    database: 0
    password: #????
